### ISSUE TITLE
install_miniconda failing on GHA ubuntu because of shell

### ISSUE THREAD

**Issue by AshesITR** [rstudio/reticulate#1317]
As reported in https://github.com/ContinuumIO/anaconda-issues/issues/13110 the install script for miniconda newly requires `bash` as a shell because it uses `[[`.

Unfortunately, `install_miniconda()` seems to use `sh` on GHA under ubuntu, as evident by build failures.

Here is the relevant step in my workflows for reference:

```yaml
      - name: install miniconda / tensorflow
        run: |
          reticulate::install_miniconda()
          tensorflow::install_tensorflow()
          tensorflow::tf$constant("Hellow Tensorflow")
        shell: Rscript {0}
```
